apiVersion: v2
name: pvault-server
description: Official Helm chart for Piiano Vault Server
type: application
version: 0.3.3
appVersion: "1.1.5"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
home: https://piiano.com/pii-data-privacy-vault/
keywords: ["piiano", "vault", "pvault", "privacy", "tokenization", "encryption", "pci"]
sources:
  - TBD