apiVersion: v2
type: application
name: pvault-server
description: Official Helm chart for Piiano Vault Server
home: https://piiano.com/pii-data-privacy-vault/
keywords: ["piiano", "vault", "pvault", "privacy", "tokenization", "encryption", "pci"]
sources:
  - https://github.com/piiano/helm-charts/tree/main/charts/pvault-server
version: 0.11.0
appVersion: 1.15.0
dependencies:
  - name: postgresql
    version: 15.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
