apiVersion: v2
name: pvault-server
description: Official Helm chart for Piiano Vault Server
type: application
version: "0.8.8"
appVersion: "1.13.3"
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
home: https://piiano.com/pii-data-privacy-vault/
keywords:
  ["piiano", "vault", "pvault", "privacy", "tokenization", "encryption", "pci"]
sources:
  - https://github.com/piiano/helm-charts/blob/main/charts/pvault-server/Chart.yaml
