apiVersion: v2
name: pvault-server
description: Official Helm chart for Piiano Vault Server
type: application
version: 0.1.0
appVersion: "1.0.2"
home: https://piiano.com/pii-data-privacy-vault/
keywords: ["piiano", "vault", "pvault", "privacy", "tokenization", "encryption", "pci"]
sources:
  - TBD