{{- if .Values.dbCARootCertificate }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "pvault-server.fullname" . }}-db-ca-cert
  labels:
    {{- include "pvault-server.labels" . | nindent 4 }}
data:
  db-ca-bundle.pem: |-
    {{ .Values.dbCARootCertificate | nindent 4 | trim }}
{{- end }}