{{- if .Values.ingress.enabled -}}
{{- if and .Values.ingress.className (not (include "pvault-server.ingress.supportsIngressClassname" .)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: {{ include "pvault-server.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "pvault-server.fullname" . }}
  namespace: {{ include "pvault-server.namespace" . | quote }}
  labels: {{- include "pvault-server.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  {{- $annotations := include "pvault-server.tplvalues.merge" (dict "values" (list .Values.ingress.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "pvault-server.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (include "pvault-server.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      secretName: {{ tpl .secretName $ | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if eq "true" (include "pvault-server.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "pvault-server.ingress.backend" (dict "serviceName" (include "pvault-server.fullname" $) "servicePort" $.Values.service.port "context" $) | nindent 14 }}
          {{- end }}
    {{- end }}
{{- end }}
