{{ $usePassword := and .Values.db.password (not .Values.db.existingPasswordSecret) }}
{{ $useAdminAPIKey := and .Values.app.adminAPIKey (not .Values.app.existingAdminAPIKeySecret) }}
{{ $useLicense := and .Values.app.license (not .Values.app.existingLicenseSecret) }}

{{- if or $usePassword $useAdminAPIKey $useLicense -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pvault-server.fullname" . }}
  labels:
    {{- include "pvault-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $usePassword }}
  pvault-db-password: {{ .Values.db.password | b64enc }}
  {{- end -}}
  {{- if $useAdminAPIKey }}
  admin-api-key: {{ .Values.app.adminAPIKey | b64enc }}
  {{- end -}}
  {{- if $useLicense }}
  license: {{ .Values.app.license | b64enc }}
  {{- end -}}
{{- end -}}