{{ $dbPass := default .Values.postgresql.auth.password .Values.pvault.db.password }} # TODO: Remove for Vault 1.1.0

{{ $usePassword := and $dbPass (not .Values.pvault.db.existingPasswordSecret) }}
{{ $useAdminAPIKey := and .Values.pvault.app.adminAPIKey (not .Values.pvault.app.existingAdminAPIKeySecret) }}
{{ $useLicense := and .Values.pvault.app.license (not .Values.pvault.app.existingLicenseSecret) }}

{{- if or $usePassword $useAdminAPIKey $useLicense -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pvault-server.fullname" . }}
  labels:
    {{- include "pvault-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $usePassword }}
  pvault-db-password: {{ $dbPass | b64enc }}
  {{- end -}}
  {{- if $useAdminAPIKey }}
  admin-api-key: {{ .Values.pvault.app.adminAPIKey | b64enc }}
  {{- end -}}
  {{- if $useLicense }}
  license: {{ .Values.pvault.app.license | b64enc }}
  {{- end -}}
{{- end -}}