{{- $dbPass := default .Values.postgresql.auth.password .Values.pvault.db.password }}
{{- $usePassword := and (not .Values.pvault.db.existingPasswordSecret) $dbPass }}
{{- $useAdminAPIKey := and (not .Values.pvault.app.existingAdminAPIKeySecret) .Values.pvault.app.adminAPIKey }}
{{- $useLicense := and (not .Values.pvault.app.existingLicenseSecret) .Values.pvault.app.license }}
{{- $useKmsSeed := and (not .Values.pvault.kms.existingSeedSecret) .Values.pvault.kms.seed }}
{{- $useKmsExportSeed := and (not .Values.pvault.kms.existingExportSeedSecret) .Values.pvault.kms.exportSeed }}
{{- /* The user is required to provide a license */}}
{{- if and (not .Values.pvault.app.license) (not .Values.pvault.app.existingLicenseSecret) }}
  {{- fail "A valid .Values.pvault.app.license or .Values.pvault.app.existingLicenseSecret is required" }}
{{- end }}
{{- if or $usePassword $useAdminAPIKey $useLicense $useKmsSeed $useKmsExportSeed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pvault-server.fullname" . }}
  namespace: {{ include "pvault-server.namespace" . | quote }}
  labels: {{- include "pvault-server.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
  {{- if or .Values.additionalSecretsAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "pvault-server.tplvalues.merge" (dict "values" (list .Values.additionalSecretsAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "pvault-server.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if $usePassword }}
  pvault-db-password: {{ $dbPass | b64enc }}
  {{- end }}
  {{- if $useAdminAPIKey }}
  admin-api-key: {{ .Values.pvault.app.adminAPIKey | b64enc }}
  {{- end }}
  {{- if $useLicense }}
  license: {{ .Values.pvault.app.license | b64enc }}
  {{- end }}
  {{- if $useKmsSeed }}
  kms-seed: {{ .Values.pvault.kms.seed | b64enc }}
  {{- end }}
  {{- if $useKmsExportSeed }}
  kms-export-seed: {{ .Values.pvault.kms.exportSeed | b64enc }}
  {{- end }}
{{- end }}
